### PR TITLE
fix(frontend): omit failing JSON:API requests 

### PR DESCRIPTION
**Pull request by fkm-adfinis**
Depends on #155 

findAll triggers requests to non-existant endpoints.

### CODE REVIEW

**Comment by velrest** [comment]
Do you know why this is happening?

**Comment by fkm-adfinis** [comment]
Nope. It is something I noticed when I changed to query to test something else.

**Comment by velrest** [comment]
@fkm-adfinis Is find all working in other parts of the app? Because if not this maybe a adapter / serializer issue.

**Comment by fkm-adfinis** [comment]
In its current form the application doesn't send out separate requests.

After looking at [the documentation](https://guides.emberjs.com/release/models/finding-records/) I figure that the separate requests are a byproduct of Ember Data's cache. But I could be wrong. I'm more familiar with `ember-apollo-client` than Ember Data. I can only guess.

**Comment by fkm-adfinis** [comment]
There is a [findAll](https://github.com/fkm-adfinis/customer-center/blob/fix/jsonapi-requests/frontend/app/services/timed.js#L66) that doesn't seem to cause any problems. Maybe it's because it doesn't have any includes.

**Review by velrest — APPROVED** [review]

**Pull request merged**
