### PR TITLE
feat(backend): update dependencies to remove security warning

### PR DESCRIPTION
**Pull request by fkm-adfinis**
And because an update has been overdue for a long time.

### CODE REVIEW

**Comment by czosel** [comment]
Did you consider using `preset-env` instead of explicit configuration? I thought that's what's recommended these days.

**Comment by czosel** [comment]
Just found this: https://gulpjs.com/docs/en/getting-started/javascript-and-gulpfiles#transpilation
Would renaming to `gulpfile.babel.js` be sufficient?

**Comment by fkm-adfinis** [comment]
> Did you consider using preset-env instead of explicit configuration? I thought that's what's recommended these days.

No. This is supposed to be a simple dependency update in order to fix the security issues. If we should change the Babel strategy and define browser requirements, I ask that you open a ticket.

> Just found this: https://gulpjs.com/docs/en/getting-started/javascript-and-gulpfiles#transpilation
> Would renaming to `gulpfile.babel.js` be sufficient?

Renaming the file worked.

**Review by czosel — APPROVED** [review]
:+1:

**Pull request merged**
