### PR TITLE
feat(frontend): update the design of the login page and add a logo

### PR DESCRIPTION
**Pull request by fkm-adfinis**
This updates the design of the login page to make the entrance to
out portal as welcoming as possible. This also adds the Adfinis
logo and narrows the language-switcher dropdown a bit.

### CODE REVIEW

**Comment by fkm-adfinis** [comment]
Screenshot_20201224_140128

**Review by velrest — COMMENTED** [review]
A lot of the css color stuff here looks like it could be handled with uikit variables instead of copy pasting the values / custom css rules. Is there a specific reason for this?

**Comment by fkm-adfinis** [comment]
I will check if I can override the variables for this scope. Should be possible.

> Is there a specific reason for this?
For the design change or the hard-coded values?

**Comment by velrest** [comment]
More for the hardcoded values but out of interest also for the design. Or more what did you improve in contrast to before since the ux is kinda hard to get from a screenshot.

**Comment by fkm-adfinis** [comment]
The hard-coded values are because it's easy :smile: 

The updated design is because the app had a fancy login page before I rewrote everything and it would be sad if the new version wouldn't also get a pretty welcome page.

**Comment by fkm-adfinis** [comment]
The design is taken from [our website](https://adfinis.com/ueber-uns/):

Screenshot_20201224_150843

**Comment by fkm-adfinis** [comment]
Updating the UIkit SCSS color variables didn't work. Probably, because I'm extending the UIkit classes.

As a compromise, I added local variables (they are not (and should not be) used anywhere else) of my own.

**Review by velrest — APPROVED** [review]

**Pull request merged**
